//TAREA 1: 
// crear variables y mostrar en pantalla ya sea con un document.write o un alert o un console.log

let nombresinApellido = "Georgina"
document.write("Mi nombre es: " + (nombresinApellido));

let edad = 32
alert("Mi edad es: " + (edad))

let carrera = true
console.log("Actualmente estoy estudiando Programación: " + (carrera));

let persona = {
  nombreyApellido:"Georgina Costilla",
  fechadeNacimiento: 1991,
  carrera: "Programación y Comunicación social",
  cursa: true
}

let listadeNumeros = [1, 2, 3, 4, 5];
console.log((listadeNumeros));